In [2]:
import tensorflow as tf

In [3]:
dropout = tf.placeholder(tf.float32)
x = tf.Variable(tf.ones([10, 10]))
y = tf.nn.dropout(x, dropout)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print("未dropout前数据")
    print(sess.run(x))
    print("dropout后数据")
    print(sess.run(y, feed_dict={dropout: 0.4}))

未dropout前数据
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
dropout后数据
[[0.  0.  0.  0.  2.5 0.  0.  2.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  2.5 0. ]
 [0.  2.5 2.5 0.  0.  0.  0.  2.5 2.5 0. ]
 [2.5 2.5 0.  0.  2.5 0.  0.  0.  2.5 0. ]
 [0.  2.5 0.  0.  0.  0.  2.5 0.  2.5 0. ]
 [0.  0.  2.5 0.  0.  0.  0.  0.  0.  2.5]
 [0.  2.5 0.  0.  2.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  2.5 0.  0.  0.  0. ]
 [0.  2.5 0.  0.  2.5 0.  0.  0.  0.  0. ]
 [2.5 2.5 2.5 0.  2.5 2.5 0.  0.  0.  0. ]]


In [11]:
dropout = tf.placeholder(tf.float32)
x = tf.Variable(tf.ones([5, 5]))
y = tf.nn.dropout(x, dropout)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print("未dropout前数据")
    print(sess.run(x))
    print("dropout后数据")
    print(sess.run(y, feed_dict={dropout: 0.4}))

未dropout前数据
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
dropout后数据
[[0.  0.  0.  2.5 2.5]
 [0.  0.  2.5 0.  2.5]
 [0.  2.5 0.  0.  2.5]
 [0.  2.5 0.  0.  2.5]
 [2.5 2.5 0.  0.  2.5]]
